#!/usr/bin/env python3
"""
lang_coverage.py — Check that every RDF resource has labels in all declared project languages.

Parses all RDF files in a repo, discovers which languages are used across the
ontology, then reports resources missing labels in any of the expected languages.

Usage:
    python lang_coverage.py <repo-path> [-o report.md] [--lang es,en,...]
      --lang : specify expected languages explicitly (otherwise auto-detect)

Requires:
    pip install rdflib
"""
import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

from rdflib import RDFS, SKOS, URIRef

from rdf_utils import load_graph, compact_uri

# Predicates we consider "label" for coverage purposes
LABEL_PREDICATES = {
    str(RDFS.label),
    str(SKOS.prefLabel),
    str(SKOS.altLabel),
}


def build_coverage_report(repo_path: str, expected_langs: list[str] | None = None) -> dict:
    """Return {resource_uri: {lang: [labels], ...}} plus auto-detected languages."""
    g, warnings = load_graph(repo_path)
    if len(g) == 0:
        return {"warnings": warnings, "resources": {}, "languages": [], "missing": []}

    # Collect all label-carrying resources
    resource_langs = defaultdict(lambda: defaultdict(list))  # resource -> lang -> [label_values]
    all_langs = set()

    for s, p, o in g.triples((None, None, None)):
        if str(p) not in LABEL_PREDICATES:
            continue
        if not hasattr(o, 'language') or not o.language:
            continue
        lang = str(o.language).lower()
        all_langs.add(lang)
        resource_langs[str(s)][lang].append(str(o))

    # Determine target languages
    if expected_langs:
        target_langs = [l.lower() for l in expected_langs]
    else:
        target_langs = sorted(all_langs)

    # Build missing report
    missing = []
    detailed = {}

    for resource_uri, lang_labels in sorted(resource_langs.items()):
        short = compact_uri(URIRef(resource_uri), g) if hasattr(g, 'namespace_manager') else resource_uri
        entry = {"resource": resource_uri, "resource_short": short, "labels": lang_labels, "missing": []}

        for tl in target_langs:
            if tl not in lang_labels:
                entry["missing"].append(tl)

        if entry["missing"]:
            missing.append(entry)

        # Also flag resources with extra unexpected languages
        extra = set(lang_labels.keys()) - set(target_langs)
        if extra:
            entry["extra_languages"] = sorted(extra)

        detailed[resource_uri] = entry

    return {
        "warnings": warnings,
        "languages_detected": sorted(all_langs),
        "target_languages": target_langs,
        "total_resources": len(resource_langs),
        "complete_resources": len(resource_langs) - len([e for e in detailed.values() if e.get("missing")]),
        "missing_count": len(missing),
        "missing": missing,
    }


def format_report_markdown(report: dict) -> str:
    lines = ["# Ontology Language Coverage Report", "",
             "_Generated by `ontology-lang-coverage` skill (rdflib)_", ""]

    if report.get("warnings"):
        for w in report["warnings"]:
            lines.append(f"- ⚠️ {w}")
        lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Languages detected | {', '.join(f'`@{l}`' for l in report['languages_detected']) or 'none'} |")
    lines.append(f"| Target languages | {', '.join(f'`@{l}`' for l in report['target_languages'])} |")
    lines.append(f"| Total labelled resources | {report['total_resources']} |")
    lines.append(f"| Complete resources | {report['complete_resources']} |")
    lines.append(f"| Resources with missing translations | {report['missing_count']} |")
    lines.append("")

    if not report["missing"]:
        lines.append("**All resources have labels in all target languages.** ✅")
        return "\n".join(lines)

    lines.append("## Resources with Missing Translations")
    lines.append("")

    for entry in report["missing"]:
        miss = ", ".join(f"`@{l}`" for l in entry["missing"])
        lines.append(f"### `{entry['resource_short']}`")
        lines.append(f"- **URI:** `{entry['resource']}`")
        lines.append(f"- **Missing:** {miss}")
        for lang, labels in sorted(entry["labels"].items()):
            lines.append(f"- @{lang}: {', '.join(f'`{lbl}`' for lbl in labels)}")
        if entry.get("extra_languages"):
            extra = ", ".join(f"`@{l}`" for l in entry["extra_languages"])
            lines.append(f"- ℹ️ Extra languages (not in target set): {extra}")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Check RDF resource label coverage across languages"
    )
    parser.add_argument("repo_path", help="Path to the ontology repository")
    parser.add_argument("-o", "--output", help="Output file (.json or .md)")
    parser.add_argument("--lang", nargs="+", default=None,
                        help="Expected languages (e.g. --lang es en fr). If omitted, auto-detect.")
    parser.add_argument("--format", choices=["json", "markdown", "report"], default="markdown")
    args = parser.parse_args()

    report = build_coverage_report(args.repo_path, expected_langs=args.lang)

    fmt = args.format
    if args.output:
        ext = Path(args.output).suffix.lower()
        if ext == ".json":
            fmt = "json"

    if fmt == "json":
        output = json.dumps(report, indent=2, ensure_ascii=False)
    elif fmt == "report":
        from report_format import AuditReport
        ar = AuditReport(skill="lang-coverage")
        for m in report.get("missing", []):
            for lang in m.get("missing", []):
                ar.add(file="—", element=m["resource_short"],
                       message=f"Missing @{lang} label", severity="warning",
                       check="missing-translation",
                       suggestion=f"Add @{lang} label for {m['resource_short']}")
            for extra in m.get("extra_languages", []):
                ar.add(file="—", element=m["resource_short"],
                       message=f"Extra language @{extra} outside target set",
                       severity="info", check="extra-language")
        output = ar.to_json()
    else:
        output = format_report_markdown(report)

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"[INFO] Report written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
