#!/usr/bin/env python3
"""
syntax_validate.py — Validate RDF syntax of all files in a repository.

Uses rapper (from raptor2) as primary validator — the reference RDF parser
supporting Turtle, RDF/XML, N-Triples, N-Quads, TriG, JSON-LD, RDFa, and more.
Falls back to rdflib if rapper is not installed.

Usage:
    python syntax_validate.py <repo-path> [-o report.md]

Requires:
    rapper (apt install raptor2-utils) — recommended
    rdflib (pip install rdflib) — fallback
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from rdf_utils import find_rdf_files

# rapper format flag per file extension
RAPPER_FORMATS = {
    ".ttl": "turtle",
    ".owl": "rdfxml",     # OWL/XML is a subset of RDF/XML
    ".rdf": "rdfxml",
    ".rdfs": "rdfxml",
    ".nt": "ntriples",
    ".nq": "nquads",
    ".trig": "trig",
    ".n3": "turtle",      # rapper handles N3 as Turtle
    ".jsonld": "guess",   # rapper auto-detects; rdflib handles better
    ".html": "rdfa",
    ".htm": "rdfa",
    ".xhtml": "rdfa",
}


def check_with_rapper(fpath: str) -> dict:
    """Validate a file with rapper. Returns {ok, error, line, col, triples}."""
    ext = Path(fpath).suffix.lower()
    fmt = RAPPER_FORMATS.get(ext)

    cmd = ["rapper", "--count"]
    if fmt:
        cmd.extend(["--input", fmt])
    cmd.append(fpath)

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "rapper timed out after 30s", "line": 0, "col": 0, "triples": 0}
    except FileNotFoundError:
        return {"ok": False, "error": "rapper not installed (apt install raptor2-utils)", "line": 0, "col": 0, "triples": 0}

    # rapper outputs everything to stderr
    stderr = result.stderr.strip()

    if result.returncode != 0 or "Error" in stderr:
        error = stderr or "Unknown rapper error"
        if len(error) > 500:
            error = error[:500] + "..."
        line_num, col_num = 0, 0
        for part in error.split("\n"):
            if "Error" in part:
                try:
                    # format: "rapper: Error - URI file:line:col: message"
                    after = part.split("Error - ")[1] if "Error - " in part else part
                    # Find line:col pattern
                    import re
                    m = re.search(r':(\d+):(\d+)', after)
                    if m:
                        line_num = int(m.group(1))
                        col_num = int(m.group(2))
                except Exception:
                    pass
        return {"ok": False, "error": error, "line": line_num, "col": col_num, "triples": 0}

    # Parse triple count from stderr: "rapper: Parsing returned X triples"
    count = 0
    for line in stderr.splitlines():
        if "returned" in line and "triples" in line:
            parts = line.strip().split()
            try:
                idx = parts.index("returned")
                count = int(parts[idx + 1])
            except (ValueError, IndexError):
                pass
    return {"ok": True, "triples": count, "error": None, "line": 0, "col": 0}


def check_with_rdflib(fpath: str) -> dict:
    """Validate a file with rdflib (fallback)."""
    from rdflib import Graph
    g = Graph()
    try:
        g.parse(fpath, format=None)  # auto-detect
        return {"ok": True, "triples": len(g), "error": None}
    except Exception as e:
        msg = str(e)
        if len(msg) > 500:
            msg = msg[:500] + "..."
        return {"ok": False, "error": msg, "line": 0, "col": 0, "triples": 0}


def validate_repo(repo_path: str, use_rapper: bool = True) -> dict:
    """Validate all RDF files. Returns structured report."""
    files = find_rdf_files(repo_path)
    if not files:
        return {"files": [], "failed": [], "ok": 0, "total": 0, "total_triples": 0}

    results = []
    failed = []
    total_triples = 0

    for fpath in files:
        rel = os.path.relpath(fpath, repo_path)
        if use_rapper:
            r = check_with_rapper(fpath)
        else:
            r = check_with_rdflib(fpath)

        r["file"] = rel
        results.append(r)

        if r["ok"]:
            total_triples += r.get("triples", 0)
        else:
            failed.append(r)

    return {
        "files": [r for r in results if r["ok"]],
        "failed": failed,
        "ok": len(results) - len(failed),
        "total": len(results),
        "total_triples": total_triples,
    }


def format_report_markdown(report: dict) -> str:
    lines = ["# RDF Syntax Validation Report", "",
             "_Generated by `ontology-syntax-validate` skill (rapper/rdflib)_", ""]

    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Files checked | {report['total']} |")
    lines.append(f"| Files OK | {report['ok']} |")
    lines.append(f"| Files with errors | {len(report['failed'])} |")
    lines.append(f"| Total triples parsed | {report['total_triples']} |")
    lines.append("")

    if not report["failed"]:
        lines.append("**All RDF files parsed successfully.** ✅")
        return "\n".join(lines)

    lines.append("## Files with Parse Errors")
    lines.append("")

    for f in report["failed"]:
        lines.append(f"### ❌ `{f['file']}`")
        if f.get('line'):
            lines.append(f"- **Line {f['line']}, col {f.get('col', '?')}**")
        lines.append(f"- **Error:**")
        lines.append(f"```")
        lines.append(f"{f['error']}")
        lines.append(f"```")
        lines.append("")

    # List OK files as reference
    if report["files"]:
        lines.append("## Files OK ({})".format(len(report["files"])))
        lines.append("")
        for f in sorted(report["files"], key=lambda x: x["file"]):
            lines.append(f"- ✅ `{f['file']}` ({f.get('triples', 0)} triples)")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Validate RDF syntax using rapper (raptor2)")
    parser.add_argument("repo_path", help="Path to the ontology repository")
    parser.add_argument("-o", "--output", help="Output file (.json or .md)")
    parser.add_argument("--rdflib", action="store_true",
                        help="Use rdflib instead of rapper for parsing")
    parser.add_argument("--format", choices=["json", "markdown", "report"], default="markdown")
    args = parser.parse_args()

    print(f"[INFO] Validating RDF files in {args.repo_path}...", file=sys.stderr)

    if not args.rdflib:
        # Check rapper availability
        try:
            subprocess.run(["rapper", "--version"], capture_output=True, timeout=5)
            use_rapper = True
        except (FileNotFoundError, subprocess.TimeoutExpired):
            print("[WARN] rapper not found — falling back to rdflib", file=sys.stderr)
            use_rapper = False
    else:
        use_rapper = False

    print(f"[INFO] Using {'rapper (raptor2)' if use_rapper else 'rdflib'}", file=sys.stderr)
    report = validate_repo(args.repo_path, use_rapper=use_rapper)

    fmt = args.format
    if args.output:
        ext = Path(args.output).suffix.lower()
        if ext == ".json":
            fmt = "json"

    if fmt == "json":
        output = json.dumps(report, indent=2, ensure_ascii=False, default=str)
    elif fmt == "report":
        from report_format import AuditReport
        ar = AuditReport(skill="syntax-validate")
        for f in report.get("failed", []):
            ar.add(file=f["file"], element="—",
                   message=f.get("error", "")[:200], severity="error",
                   check="parse-error", line=f.get("line", 0))
        output = ar.to_json()
    else:
        output = format_report_markdown(report)

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"[INFO] Report written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
